apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: cinematic-monorepo
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: toydb
    context: toydb
  - image: cinematic/backend
    context: backend
    docker:
      dockerfile: Dockerfile
    sync:
      infer:
      - 'app'
      - 'requirements.txt'
  - image: cinematic/model_server
    context: model_server
    docker:
      dockerfile: Dockerfile
    sync:
      infer:
      - 'app'
      - 'keys_dict.json'
      - 'requirements.txt'
  - image: cinematic/frontend
    context: frontend_new
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kustomize:
        paths: ["kustomize/overlays/dev"]
  - name: prod
    patches:
    - op: remove
      path: /build/artifacts/0
    deploy:
      kustomize:
        paths: ["kustomize/overlays/prod"]
