apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: cinematic-monorepo
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: cinematic/backend
    context: backend
    docker:
      dockerfile: Dockerfile.server
  - image: cinematic/db_migration
    context: backend
    docker:
      dockerfile: Dockerfile.db_migration
  # TODO enable once build time is reasonable
  # - image: cinematic/model_server
  #   context: model_server
  #   docker:
  #     dockerfile: Dockerfile
  #   sync:
  #     infer:
  #     - 'app'
  #     - 'keys_dict.json'
  #     - 'requirements.txt'
  - image: cinematic/frontend
    context: frontend_new
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kustomize:
        paths: ["kustomize/overlays/dev"]
  - name: prod
    deploy:
      kustomize:
        paths: ["kustomize/overlays/prod"]
