FROM clearlinux/golang:1.15 as builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -a -v -o db_migration ./cmd/db_migration

FROM clearlinux:latest

WORKDIR /dist

COPY --from=builder /build/db_migration .
COPY schema/ ./schema/

CMD ["./db_migration"]
