kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: backend
  type: ClusterIP
