kind: Service
apiVersion: v1
metadata:
  name: toydb
  labels:
    app: toydb 
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: toydb
  type: ClusterIP
