name: Code Quality

on:
  pull_request:
    branches:
    - main 

jobs:
  python_lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "backend"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-black: true
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: "--check"
          extra-mypy-options: ""
          extra-isort-options: ""
